### ISSUE TITLE
How to solve TypeError: unhasable type: 'dict' ?

### ISSUE THREAD

**Issue by sahelib25** [mlcommons/tiny_results_v1.0#1]
I am trying to reproduce the results for tiny v1.0 submitted by OctoML.
```
saheli@chai:~$ cm run script --tags=generate,tiny,mlperf,octoml,submission

* Searching for collective script(s) with tags "generate,tiny,mlperf,octoml,submission"
  - Number of scripts found: 1
  - Found script::wrapper-reproduce-octoml-tinyml-submission,b946001e289c4480 in /home/saheli/CM/repos/mlcommons@ck/cm-mlops/script/wrapper-reproduce-octoml-tinyml-submission
    - Requested version:  == {'r1.0': {}}
Traceback (most recent call last):
  File "/home/saheli/.local/bin/cm", line 8, in <module>
    sys.exit(run())
  File "/home/saheli/.local/lib/python3.10/site-packages/cmind/cli.py", line 35, in run
    r = cm.access(argv, out='con')
  File "/home/saheli/.local/lib/python3.10/site-packages/cmind/core.py", line 493, in access
    r = action_addr(i)
  File "/home/saheli/CM/repos/mlcommons@ck/cm-mlops/automation/script/module.py", line 832, in run
    if version!='' and version in versions:
TypeError: unhashable type: 'dict'
```

**Comment by arjunsuresh** [comment]
Hi @sahelib25 Thank you for filing the issue. This is due to an unfortunate [typo](https://github.com/mlcommons/ck/pull/596/files#diff-5b6adf0a4769dc971668afecb877d2b3d0ca316c2bf42f5e3821dd3d702199a1) which is fixed now.
Can you please do
```
cm pull repo mlcommons@ck
```
and retry the commands?

**Comment by gfursin** [comment]
Thank you very much for your feedback, @sahelib25 ! 

By the way, please consider joining the [MLCommons taskforce on education and reproducibility](https://github.com/mlcommons/ck/blob/master/docs/mlperf-education-workgroup.md) - we always welcome such feedback to continuously improve CM framework and help the community automate design space exploration of ML Systems! 

We have added CM tests for MLPerf inference but did not have time to add tests for TinyMLPerf - we will discuss it during our next meeting in January! 

Happy holidays!

**Comment by gfursin** [comment]
I have merged the fix from @arjunsuresh with the mainline mlcommons@ck . 

@sahelib25 , please do not forget to update the main automation repository and try again:

```bash
cm pull repo mlcommons@ck
```

Thanks!

**Comment by sahelib25** [comment]
Thank you @arjunsuresh and @gfursin for the fix.
